Dev/0.0.1
RIT-EVT/APM pull request #1
Opened 2021-08-24 14:43 UTC by ddp5730

Initialization of project structure and cmake build files.  All actual APM code is currently a placeholder to test build system.

- I'm interested in any suggestions so that less of the CmakeLists.txt files are copy and pasted between projects.

2021-08-24 14:44 UTC, ddp5730 commented on CMakeLists.txt
> +                            -T ${PROJECT_SOURCE_DIR}/libs/EVT-core/libs/HALf3/STM32F302C8Tx_FLASH.ld \
I'm curious if anyone has suggestions on how to better link this file.

2021-08-25 15:59 UTC, agm3067 requested changes
I think overall this looks really great!  The only change that I think would be nice to have is for the README.md to link to our confluence page either above or below the system architecture diagram.  Feel free to not make this change, I just think that link might be helpful.

2021-08-25 16:14 UTC, agm3067 approved these changes

2021-08-30 13:34 UTC, cbolles approved these changes

2021-08-30 14:02 UTC, merged