Switch test
RIT-EVT/APM pull request #10
Opened 2022-03-29 00:17 UTC by ddp5730

This is an extra target that is useful for manually controlling the hardware switches on the APM.  Used primarily by the electical team.

2022-03-29 00:32 UTC, cbolles requested changes
Just a couple of stylistic suggestions

2022-03-29 00:32 UTC, cbolles commented on src/APM/dev/SIM100.cpp
> +//    if (!expectResponse) {
Should this commented code be left in? If so add a comment explaining why the code is commented out.

2022-03-29 00:32 UTC, cbolles commented on targets/switch-test/switch_test.cpp
> +EVT::core::IO::GPIO::State get_toggle(EVT::core::IO::GPIO::State state) {
Should be camel case for style (Can bring in the clang-format support from the project template).

2022-03-29 18:46 UTC, AarC10 approved these changes
Great work. Don't think I have any issues besides the style issues Collin mentioned. Just mostly more questions to continue getting a better idea of how the system works and things to think about for future

2022-03-29 18:46 UTC, AarC10 commented on targets/switch-test/switch_test.cpp
> +        if (strncmp("h", APM::buf, APM::BUF_SIZE) == 0) {
This is more of a question since it is just a test, but wouldn't it be more optimal to utilize a switch-case

2022-03-29 18:46 UTC, AarC10 commented on src/APM/dev/SIM100.cpp
> -        // TODO: Implement timeout and return something accordingly.  Also better error handling
Another question. What kind of errors should we be expecting and handling?

2022-03-30 00:58 UTC, mjmagee991 approved these changes
Looks good. Didn't see anything else that needs changing

2022-05-28 17:43 UTC, merged